# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

KingdomBuilder.create([ { name: 'AYENI OLUWABUSAYO',
                        email: 'ayenibusayo1@gmail.com',
                        phone_number: '08164661450',
                        parish: 'His Majesty\'s Place',
                        area: 'His Majesty\'s Place',
                        zone: 1,
                        payment_mode: 'quarterly',
                        amount_pledge: 40000,
                        total_amount_paid: 0,
                        payment_mode_based_amount: 5000,
                        status: 'awaiting',
                        entered_by: ''},
                      { name: 'BODE THOMAS',
                        email: 'ojutaiyebode@yahoo.com',
                        phone_number: '08033259438',
                        parish: 'His Majesty\'s Place',
                        area: 'His Majesty\'s Place',
                        zone: 1,
                        payment_mode: 'monthly',
                        amount_pledge: 480000,
                        total_amount_paid: 0,
                        payment_mode_based_amount: 20000,
                        status: 'awaiting',
                        entered_by: ''},
                      { name: 'BABATUNDE OPEYEMI OLUWAFUNMILAYO',
                        email: 'babatundeopeyemi1305@gmail.com',
                        phone_number: '07015864862',
                        parish: 'His Majesty\'s Place',
                        area: 'His Majesty\'s Place',
                        zone: '1',
                        payment_mode: 'monthly',
                        amount_pledge: 48000,
                        total_amount_paid: 0,
                        payment_mode_based_amount: 2000,
                        status: 'awaiting',
                        entered_by: ''},
                      { name: 'CHIDINMA IJEOMAH',
                        email: 'chichiofeogbu@yahoo.com',
                        phone_number: '08023392665',
                        parish: 'His Majesty\'s Place',
                        area: 'His Majesty\'s Place',
                        zone: '1',
                        payment_mode: 'monthly',
                        amount_pledge: 120000,
                        total_amount_paid: 0,
                        payment_mode_based_amount: 5000,
                        status: 'awaiting',
                        entered_by: ''},
                      { name: 'SHEDRACK IJEOMAH',
                        email: 'shedeco@yahoo.com',
                        phone_number: '08038587631',
                        parish: 'His Majesty\'s Place',
                        area: 'His Majesty\'s Place',
                        zone: '1',
                        payment_mode: 'monthly',
                        amount_pledge: 120000,
                        total_amount_paid: 0,
                        payment_mode_based_amount: 5000                                                             ,
                        status: 'awaiting',
                        entered_by: ''},
                      { name: 'BIMBO GRACE OJUTAIYE',
                        email: 'ojutaiye_bimbo@yahoo.com',
                        phone_number: '08055603504',
                        parish: 'His Majesty\'s Place',
                        area: 'His Majesty\'s Place',
                        zone: '1',
                        payment_mode: 'monthly',
                        amount_pledge: 120000,
                        total_amount_paid: 0,
                        payment_mode_based_amount: 5000,
                        status: 'awaiting',
                        entered_by: ''},
                      { name: 'WILLIAMS KEHINDE',
                        email: 'kehindewilliams77@gmail.com',
                        phone_number: '08179849121',
                        parish: 'His Majesty\'s Place',
                        area: 'His Majesty\'s Place',
                        zone: '1',
                        payment_mode: 'monthly',
                        amount_pledge: 120000,
                        total_amount_paid: 0,
                        payment_mode_based_amount: 5000,
                        status: 'awaiting',
                        entered_by: ''},
                      { name: 'ADISA IBRAHIM OLASUNKANMI',
                        email: 'sulihrip@gmail.com',
                        phone_number: '07049117554',
                        parish: 'His Majesty\'s Place',
                        area: 'His Majesty\'s Place',
                        zone: '1',
                        payment_mode: 'quarterly',
                        amount_pledge: 4000000,
                        total_amount_paid: 0,
                        payment_mode_based_amount: 500000,
                        status: 'awaiting',
                        entered_by: ''},
                      { name: 'ODO VICTORIA',
                        email: 'victoriaodo2017@gmail.com',
                        phone_number: '08023015603',
                        parish: 'His Majesty\'s Place',
                        area: 'His Majesty\'s Place',
                        zone: '1',
                        payment_mode: 'monthly',
                        amount_pledge: 120000,
                        total_amount_paid: 0,
                        payment_mode_based_amount: 5000,
                        status: 'awaiting',
                        entered_by: ''},
                      { name: 'OKON FERANMI FANE OSONG',
                        email: 'okunoluwaferonmi@gmail.com',
                        phone_number: '09036413813',
                        parish: 'His Majesty\'s Place',
                        area: 'His Majesty\'s Place',
                        zone: '1',
                        payment_mode: 'monthly',
                        amount_pledge: 72000,
                        total_amount_paid: 0,
                        payment_mode_based_amount: 3000,
                        status: 'awaiting',
                        entered_by: ''},
                      { name: 'ODUYOYE FAMILY',
                        email: 'oreoluwaoduyoye@yahoo.com',
                        phone_number: '08035066810',
                        parish: 'His Majesty\'s Place',
                        area: 'His Majesty\'s Place',
                        zone: '1',
                        payment_mode: 'monthly',
                        amount_pledge: 16000000,
                        total_amount_paid: 0,
                        payment_mode_based_amount: 2000000,
                        status: 'awaiting',
                        entered_by: ''} ])