# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Zone.create(
      [
        {name: 'His Majesty\'s Place'},
        {name: 'Liberty'}
      ]
)

Area.create([
              { name: 'His Majesty\'s Place', zone_id: 1 },
              { name: 'Liberty', zone_id: 2 }
            ])


Parish.create([
              { name: 'His Majesty\'s Place', areas_id: 1},
              { name: 'Maranatha', areas_id: 1},
              { name: 'Signs and Wonders', areas_id: 2},
              { name: 'Christ The Light', areas_id: 2},
              { name: 'Overcomers', areas_id: 2}
            ])

KingdomBuilder.create([ { name: 'AYENI OLUWABUSAYO',
                        email: 'ayenibusayo1@gmail.com',
                        phone_number: '08164661450',
                        parishes_id: 1,
                        areas_id: 1,
                        zone_id: 1,
                        payment_mode: 'quarterly',
                        amount_pledge: 40000,
                        total_amount_paid: 0,
                        payment_mode_based_amount: 5000,
                        status: 'awaiting',
                        pledge_type: 'cash',
                        entered_by: 'Nelson'},
                      { name: 'BODE THOMAS',
                        email: 'ojutaiyebode@yahoo.com',
                        phone_number: '08033259438',
                        parishes_id: 2,
                        areas_id: 1,
                        zone_id: 1,
                        payment_mode: 'monthly',
                        amount_pledge: 480000,
                        total_amount_paid: 0,
                        payment_mode_based_amount: 20000,
                        status: 'awaiting',
                        pledge_type: 'cash',
                        entered_by: 'Nelson'},
                      { name: 'BABATUNDE OPEYEMI OLUWAFUNMILAYO',
                        email: 'babatundeopeyemi1305@gmail.com',
                        phone_number: '07015864862',
                        parishes_id: 6,
                        areas_id: 2,
                        zone_id: 2,
                        payment_mode: 'monthly',
                        amount_pledge: 48000,
                        total_amount_paid: 0,
                        payment_mode_based_amount: 2000,
                        status: 'awaiting',
                        pledge_type: 'cash',
                        entered_by: 'Nelson'},
                      { name: 'CHIDINMA IJEOMAH',
                        email: 'chichiofeogbu@yahoo.com',
                        phone_number: '08023392665',
                        parishes_id: 7,
                        areas_id: 2,
                        zone_id: 2,
                        payment_mode: 'monthly',
                        amount_pledge: 20000,
                        total_amount_paid: 0,
                        payment_mode_based_amount: 5000,
                        status: 'awaiting',
                        pledge_type: 'cash',
                        entered_by: 'Nelson'},
                      { name: 'SHEDRACK IJEOMAH',
                        email: 'shedeco@yahoo.com',
                        phone_number: '08038587631',
                        parishes_id: 8,
                        areas_id: 2,
                        zone_id: 2,
                        payment_mode: 'monthly',
                        amount_pledge: 20000,
                        total_amount_paid: 0,
                        payment_mode_based_amount: 5000                                                             ,
                        status: 'awaiting',
                        pledge_type: 'cash',
                        entered_by: 'Nelson'},
                      { name: 'BIMBO GRACE OJUTAIYE',
                        email: 'ojutaiye_bimbo@yahoo.com',
                        phone_number: '08055603504',
                        parishes_id: 1,
                        areas_id: 1,
                        zone_id: 2,
                        payment_mode: 'monthly',
                        amount_pledge: 20000,
                        total_amount_paid: 0,
                        payment_mode_based_amount: 5000,
                        status: 'awaiting',
                        pledge_type: 'cash',
                        entered_by: 'Nelson'},
                      { name: 'WILLIAMS KEHINDE',
                        email: 'kehindewilliams77@gmail.com',
                        phone_number: '0817984921',
                        parishes_id: 2,
                        areas_id: 1,
                        zone_id: 2,
                        payment_mode: 'monthly',
                        amount_pledge: 20000,
                        total_amount_paid: 0,
                        payment_mode_based_amount: 5000,
                        status: 'awaiting',
                        pledge_type: 'cash',
                        entered_by: 'Nelson'},
                      { name: 'ADISA IBRAHIM OLASUNKANMI',
                        email: 'sulihrip@gmail.com',
                        phone_number: '07049117554',
                        parishes_id: 6,
                        areas_id: 2,
                        zone_id: 2,
                        payment_mode: 'quarterly',
                        amount_pledge: 4000000,
                        total_amount_paid: 0,
                        payment_mode_based_amount: 500000,
                        status: 'awaiting',
                        pledge_type: 'cash',
                        entered_by: 'Nelson'},
                      { name: 'ODO VICTORIA',
                        email: 'victoriaodo2017@gmail.com',
                        phone_number: '08023015603',
                        parishes_id: 7,
                        areas_id: 2,
                        zone_id: 2,
                        payment_mode: 'monthly',
                        amount_pledge: 20000,
                        total_amount_paid: 0,
                        payment_mode_based_amount: 5000,
                        status: 'awaiting',
                        pledge_type: 'cash',
                        entered_by: 'Nelson'},
                      { name: 'OKON FERANMI FANE OSONG',
                        email: 'okunoluwaferonmi@gmail.com',
                        phone_number: '09036413813',
                        parishes_id: 7,
                        areas_id: 2,
                        zone_id: 2,
                        payment_mode: 'monthly',
                        amount_pledge: 72000,
                        total_amount_paid: 0,
                        payment_mode_based_amount: 3000,
                        status: 'awaiting',
                        pledge_type: 'cash',
                        entered_by: 'Nelson'},
                      { name: 'ODUYOYE FAMILY',
                        email: 'oreoluwaoduyoye@yahoo.com',
                        phone_number: '08035066810',
                        parishes_id: 8,
                        areas_id: 2,
                        zone_id: 2,
                        payment_mode: 'monthly',
                        amount_pledge: 16000000,
                        total_amount_paid: 0,
                        payment_mode_based_amount: 2000000,
                        status: 'awaiting',
                        pledge_type: 'cash',
                        entered_by: 'Nelson'}
                      ])